# Generated by Django 5.2.12 on 2026-03-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamtelegramconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='anthropic_api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='openai_api_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
