# Generated by Django 5.2.12 on 2026-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_anthropic_api_key_team_openai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgmailconfig',
            name='google_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamgmailconfig',
            name='google_client_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teamgmailconfig',
            name='credentials_json',
            field=models.TextField(blank=True, default='', help_text='OAuth token JSON. Will be encrypted in a future release.'),
        ),
        migrations.AlterField(
            model_name='teamgmailconfig',
            name='watch_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
