# Generated by Django 5.2.1 on 2026-03-19 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamgmailconfig_google_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMessengerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_access_token', models.TextField(help_text='Page Access Token from Facebook Developer Portal.')),
                ('page_id', models.CharField(blank=True, default='', help_text='Facebook Page ID. Used to route webhooks.', max_length=255)),
                ('verify_token', models.CharField(max_length=255)),
                ('instagram_enabled', models.BooleanField(default=False, help_text='When True, messages from this page are treated as Instagram DMs.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_config', to='teams.team')),
            ],
            options={
                'db_table': 'team_messenger_configs',
            },
        ),
    ]
