# Generated by Django 5.2.12 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teammessengerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgmailconfig',
            name='last_poll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
