# Generated by Django 5.2.12 on 2026-03-15 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('low_confidence', 'Low AI Confidence'), ('negative_sentiment', 'Negative Sentiment'), ('customer_request', 'Customer Requested Human'), ('guardrail_flag', 'Guardrail Flagged')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the conversation so far')),
                ('suggested_response', models.TextField(blank=True, help_text='AI-suggested response for the human agent')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='core.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
