# Generated by Django 5.2.12 on 2026-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cannedresponse_tag_internalnote_conversationtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webchat', 'Web Chat'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
