# Generated by Django 5.2.12 on 2026-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_conversation_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='human_only',
            field=models.BooleanField(default=False),
        ),
    ]
