# Generated by Django 5.2.12 on 2026-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_human_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webchat', 'Web Chat'), ('telegram', 'Telegram'), ('messenger', 'Messenger'), ('instagram', 'Instagram')], max_length=20),
        ),
    ]
